spring.application.name=PASiR_Zajac_Lukasz
spring.config.import=optional:file:.env[.properties]
# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/${MYSQL_DATABSE:zajac_lukasz_k05_spring}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=${MYSQL_USER:user-zl}
spring.datasource.password=${MYSQL_PASSWORD:student1}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.graphql.http.path=/graphql
spring.graphql.schema.file-extensions=.graphql, .graphqls, .gqls
app.jwt.secret=TwojBardzoDlugiISkomplikowanyKluczKtoryMaPrzynajmniej64Znaki12345678901234567890